[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = [
  "npx prisma generate --schema prisma/schema.prisma",
  "npx prisma db push --schema prisma/schema.prisma --accept-data-loss"
]

[start]
cmd = "npm start"
